dinfuehr/dora

src/masm/x64.rs, tests/float15.dora
This change is hopefully in line with what you suggested!
I opted for some small code duplication, because I found it to be more readable, let me know if you like the change made differently!
=> Fix #17: Swap arguments on floating point comparison to handle NaN correctly

src/bytecode/astgen.rs, src/bytecode/generate.rs, src/bytecode/opcode.rs
string pool is currently not emitted into the bytecode.
=> reference const string literals as index of string pool

stdlib/Option.dora, stdlib/Stringable.dora, tests/option.dora, tests/stringable.dora
This adds a `Stringable` trait (maybe I find a better name in the future :-)) and an implementation of an `Option` class.¹
¹ As far as I understand, we do not have support for lambdas yet?
=> Add trait Stringable and class Option

dora/src/baseline/cannon/codegen.rs
This PR adds support to load fields from an object or global fields. Nothing fancy.
It is based on #102, if this is a problem, I can try to rebase the changes to the current master.
=> cannon: load object and global fields

dora/src/baseline/ast/codegen.rs, dora/src/baseline/cannon/codegen.rs, dora/src/baseline/fct.rs, dora/src/bytecode/generate.rs, dora/src/bytecode/opcode.rs, dora/src/class.rs, dora/src/field.rs, dora/src/lib.rs, dora/src/object.rs, dora/src/semck/clsdefck.rs, dora/src/semck/prelude.rs, dora/src/semck/specialize.rs, dora/src/semck/superck.rs, dora/src/size.rs, dora/src/vm.rs, dora/src/vtable.rs
These are refactorings salvaged from #88.
=> Split field and size into separate files

dora-parser/src/ast.rs, dora-parser/src/ast/dump.rs, dora-parser/src/ast/visit.rs, dora-parser/src/lexer.rs, dora-parser/src/lexer/token.rs, dora-parser/src/parser.rs
These are the first round of changes salvaged from #88.
(My approach now would be to add these things step-by-step as you proposed, such that the PR doesn't become completely full of conflicts.)
=> Add modules to AST and parser

dora/stdlib/Double.dora, dora/stdlib/Float.dora, dora/stdlib/Sortable.dora, tests/srt.dora
=> Implement Sortable for Float and Double

dora/stdlib/String.dora, tests/string/string-toString.dora
=> Implement String#toString to avoid stack overflow

dora/stdlib/Bool.dora, dora/stdlib/Byte.dora, dora/stdlib/Double.dora, dora/stdlib/Float.dora, dora/stdlib/Int.dora, dora/stdlib/Long.dora, dora/stdlib/String.dora, tests/bool1.dora, tests/byte1.dora, tests/double0.dora, tests/float0.dora, tests/int1.dora, tests/long3.dora
This change adds a helper function that's helpful when working with bits.
This is certainly not the most elegant, elaborate or flexible approach
(compared to languages that support arbitrary bases or compared to a
typeclass-based design that enables a maximum of abstraction), but it is
simple and straight-forward and should last until a better solution is
required.
=> Add {Int,Long,Float,Double,Bool}#toStringBinary

dora/src/baseline/codegen.rs, dora/src/compiler/asm.rs, dora/src/cpu/x64/asm.rs, dora/src/masm/x64.rs, dora/src/semck/prelude.rs, dora/src/typeck/tests.rs, dora/src/vm/fct.rs, dora/stdlib/Double.dora, dora/stdlib/Int.dora, dora/stdlib/Long.dora, dora/stdlib/Random.dora, dora/stdlib/String.dora, tests/int-shift-rotate.dora, tests/int1.dora, tests/long-shift-rotate.dora, tests/long3.dora
More operations for https://github.com/dinfuehr/dora/issues/117.
=> Implement {Int,Long}#{rotateLeft,rotateRight}

dora-boots/ssagen.dora, dora/stdlib/HashMap.dora, tests/stdlib/hashmap1.dora, tests/stdlib/hashmap2.dora
As suggested in https://github.com/dinfuehr/dora/pull/128#issuecomment-571072355.
=> Convert HashMap from nil to Option

dora/src/masm/x64.rs
As mentioned in https://github.com/dinfuehr/dora/pull/144.
=> Move "mode to w-bit" pattern match to function

dora/src/semck/prelude.rs
A few minutes too late for https://github.com/dinfuehr/dora/pull/131. :-)
=> Fail when we are trying to install an intrinsic for a method not marked @internal

dora/src/object.rs, dora/src/stdlib.rs, dora/stdlib/BitSet.dora, dora/stdlib/Error.dora, dora/stdlib/Exception.dora, dora/stdlib/String.dora, dora/stdlib/StringBuffer.dora, dora/stdlib/Vec.dora, tests/exception/print-stack-trace1.dora, tests/string/string-fromBytes.dora, tests/string/string-main.dora
Additional pieces extracted from https://github.com/dinfuehr/dora/pull/128.
=> Drop nil from Vec, BitSet, String, Exception and Error

dora/stdlib/CodepointIterator.dora, dora/stdlib/Equals.dora, dora/stdlib/HashMap.dora, dora/stdlib/IntRange.dora, dora/stdlib/Iterator.dora, dora/stdlib/prelude.dora, tests/stdlib/hashmap1.dora, tests/stdlib/hashmap2.dora
=> Various library work

dora/stdlib/HashSet.dora, tests/stdlib/hashset1.dora, tests/stdlib/hashset2.dora
Shamelessly stolen from the HashMap code.
=> Add HashSet implementation

tests/cannon/int1.dora
=> cannon: add test for int negation

dora/stdlib/Bool.dora, tests/bool-tostring.dora, tests/bool1.dora, tests/byte-tostring.dora, tests/byte1.dora, tests/int-tostring.dora, tests/int1.dora, tests/long-tostring.dora, tests/long3.dora
Together with the impl written by @dinfuehr earlier, this should close https://github.com/dinfuehr/dora/issues/124.
=> Add Bool#toStringHex (for consistency with toStringBinary) and add tests for Bool, Int, Long

dora/src/cpu/x64.rs, dora/src/cpu/x64/asm.rs, dora/src/masm/x64.rs
Follow-up to https://github.com/dinfuehr/dora/pull/138.
=> Use shift instructions that don't set flags where available

dora/src/cpu/x64/asm.rs, dora/src/masm/x64.rs
Follow-up to https://github.com/dinfuehr/dora/pull/144.
=> Migrate from w() to is64()

bench/binarytrees/binarytrees.dora, bench/gcbench/gcbench.dora, bench/gcold/gcold.dora, bench/splunc/splunc.dora, dora-boots/assembler.dora, dora-boots/dominator_test.dora, dora-boots/ssagen_block.dora, dora-boots/ssagen_tests.dora, dora-parser/src/ast.rs, dora-parser/src/builder.rs, dora-parser/src/parser.rs, dora/src/bytecode/generator_tests.rs, dora/src/semck/nameck.rs, dora/src/typeck/tests.rs, dora/stdlib/String.dora, dora/stdlib/Vec.dora
=> Drop `var` keyword in parameter list

bench/falsesharing/falsesharing.dora
=> Fix compilation errors in falsesharing.dora

dora/src/bytecode/generator.rs, dora/src/driver/start.rs, dora/src/gc.rs, dora/src/object.rs, dora/src/semck/clsdefck.rs, dora/src/semck/fctdefck.rs, dora/src/semck/moduledefck.rs, dora/src/semck/prelude.rs, dora/src/stack.rs, dora/src/ty.rs, dora/src/typeck/expr.rs, dora/src/vm.rs, dora/src/vm/class.rs, dora/src/vm/known.rs
@dinfuehr Let me know if you dislike any of the renames ... I tried to use "speaking" names while trying to reflect the structure closely.
=> Sort individual members of KnownElements into KnownClasses/KnownModules/KnownTraits/KnownFunctions structs

dora-parser/src/parser.rs, tests/precedence.dora
Fixes https://github.com/dinfuehr/dora/issues/240.
=> Adjust precedence of &

tests/array/array-sortStable.dora
Should probably close https://github.com/dinfuehr/dora/issues/256.
=> stdlib: more tests and documentation for Array.sortStable

dora-asm/src/arm64.rs, dora-asm/src/x64.rs, dora/src/cannon/codegen.rs, dora/src/compiler/asm.rs, dora/src/cpu/x64.rs, dora/src/language/stdlib.rs, dora/src/masm/arm64.rs, dora/src/masm/x64.rs, dora/src/vm/functions.rs, dora/stdlib/Float32.dora, dora/stdlib/Float64.dora, tests/float/float32-roundDown.dora, tests/float/float32-roundHalfEven.dora, tests/float/float32-roundToZero.dora, tests/float/float32-roundUp.dora, tests/float/float64-roundDown.dora, tests/float/float64-roundHalfEven.dora, tests/float/float64-roundToZero.dora, tests/float/float64-roundUp.dora
See https://github.com/dinfuehr/dora/issues/140.
=> stdlib: implement first rounding methods for `Float32` and `Float64`
