dinfuehr/dora

- src/baseline/expr.rs
- src/semck/typeck.rs
- stdlib/prelude.dora
- tests/generic-array-has.dora
- tests/identity.dora
- tests/nil2.dora
- Already worked for references
- Now works for whole numbers (same as ==)
- Now works for floating point numbers such that
float1  === float2  ----> float1.asInt()   == float2.asInt()
double1 === double2 ----> double1.asLong() == double2.asLong()
> Identity comparison (===) works on all types

- src/semck/superck.rs
Fixes the build errors in Travis seen in #71.
Error happened, when a class was processed after a subclass of it was processed. `determine_vtable` was called for the subclass, which recursivle called `determine_vtable` for the parent. After that, in `determine_vtables` the loop at some point also called `determine_vtable` for the parent. Because the vtable was already created, the assertion in line number 72 failed.
If the order of the classes was different (as on my local system), the `determine_vtable` was first called for the parent class. When now `determine_vtable` was called for the subclass, it correctly checked the HashSet, if we already processed the parent and skipped the call.
I added a check before calling `determine_vtable` in `determine_vtables`.
> added check in determine_vtable to skip already processed class

- src/baseline/ast/expr.rs
- src/baseline/ast/info.rs
- src/ctxt.rs
- src/exception.rs
- src/object.rs
- src/semck/prelude.rs
- src/semck/superck.rs
- src/test.rs
- stdlib/Error.dora
- stdlib/Exception.dora
- stdlib/Throwable.dora
- tests/assert2.dora
- tests/assert3.dora
- tests/exception/print-stack-trace4.dora
- tests/stdlib/call-assert.dora
- tools/tester.rb
I changed assert so it will throw an Error. Addiotionally, i added abstract Throwable class to stdlib, which is the base class for the existing Exception and the newly introduced Error. This behavior is similar to the behavior of Java.
> baseline: assert throws Error instead of trap 

- .vscode/settings.json
I ran into the following issue on my work station: https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
I added the target folders to the exclude settings of vscode and this fixed the problem for me. 
To be thorough: `cat /proc/sys/fs/inotify/max_user_watches` shows, that I have a maximum of 8192 handles. Currently, after I cleaned my target folders and built the project twice (debug and release), I get the following output:
```
$ find . -type f | wc -l
8168
$ find lib/dora-parser/target -type f | wc -l
2993
$ find target -type f | wc -l
3366
```
So around 75% of the files are related to building the project.
> vscode: fixed error "unable to watch for file changes in large work space"

- .vscode/settings.json
The changes in #83 didn't work as I thought. After I restarted my computer and Visual Code the message came up again. I digged a little deeper into the matter and realized, that the pattern has to match the absolute path. I changed it accordingly to match all target folders. This is naturally not perfect, but as long we don't create a folder named target, this should be unproblematic.
> vscode: fixed watcher exclude to match absolute path (fixes #83)

- src/baseline/cannon/codegen.rs
- src/bytecode/generate.rs
I added support for literal values in cannon for Char, Byte, Int, Long, Float, Double and String. Tests are currently not possible, because most rely heavily on assert. But with `--emit-asm=all` it is possible to compare the output of both baseline-compiler. (#86 is needed)
> cannon: emit code for char, string, int and float constants

- src/bytecode/generate.rs
`align_i32` seems to not work correctly with negative numbers. Simple solution with some changes of operators and signs.
> bytecode: fix calculation of stacksize

- src/bytecode/astgen.rs
- src/bytecode/generate.rs
- src/bytecode/opcode.rs
As discussed, the intrinsic assert is translated into the corresponding code, as it will be executed. This is similar to the approach Java is using.
> bytecode: add assert/throw support to bytecode

- .github/workflows/lint-and-test.yml
- README.md
I figured out that capstone is not needed as an external dependency anymore.
we are using capstone-rs, which is compiling capstone for us https://github.com/capstone-rust/capstone-rs/blob/master/capstone-sys/build.rs
The good news is we can also install with `cargo install dora`.
You only have to publish the project on crates.io https://doc.rust-lang.org/cargo/reference/publishing.html
> Capstone not needed as external dependency

- src/baseline/cannon/codegen.rs
- src/bytecode/generate.rs
This PR adds support for various simple bytecode types, like arithmetic, compare and logical operations. Missing bytecodes include load, invoke, jump, new object and throw, as well some currently not existing bytecodes. I will implement them as soon as possible and add them to this PR or create a new one.
> cannon: add support for various bytecodes

- dora/src/baseline/asm.rs
- dora/src/baseline/cannon/codegen.rs
- dora/src/baseline/codegen.rs
- dora/src/bytecode/astgen.rs
- dora/src/bytecode/generate.rs
- dora/src/masm.rs
This PR adds support for the bytecodes for Jump, JumpIfTrue & JumpIfFalse. To resolve forward jumps, I added a Map from bytecode index to address, which is then used to create a label at a specific position. 
Additionally I fixed two small errors:
- a if expession, which returns a Unit, crashed the bytecode generator
- a return inside the code did not exit the function
> cannon: support for jump

- dora/src/baseline/cannon/codegen.rs
- tests/cannon/abi1.dora
- tests/cannon/abi2.dora
Because of PR #105 we can now call functions, which are run with cannon. As a consequence cannon has to handle function arguments. 
As every argument gets its own Register assigned when the bytecode is generated, I copy stack arguments to their respective local stack.
Additionally, I added some tests. Currently they are ignored, as some functionality is missing.
> cannon: copy function arguments to local stack

- dora/src/baseline/cannon/codegen.rs
- tests/cannon/loadfield1.dora
The implementation field loads in cannon didn't consider, that the temporary register should correspond to the machine mode. 
Moreover, I added a test, which immediately showed, that I missed the RetPtr bytecode, when I implemented the various Ret*.
> cannon: fix load fields

- dora/src/baseline/cannon/codegen.rs
- dora/src/bytecode/astgen.rs
- dora/src/bytecode/encoding.rs
- dora/src/bytecode/generate.rs
- dora/src/bytecode/opcode.rs
- tests/cannon/float1.dora
Based on PR #111 
Adds arithmetic (-,+,/,*) and compare operations (==,!=,<,<=,>=,>) for Float to the bytecode generator and cannon. Includes a simple test for these operations.
Some small fixes in the dump() function of the bytecode generator are also included. The strings didn't always represent the operation correctly. ;)
> cannon: float operations

- dora/src/bytecode/generator.rs
- dora/src/bytecode/generator_tests.rs
- dora/src/bytecode/writer.rs
- dora/src/cannon/codegen.rs
- tests/cannon/ctor1.dora
- tests/cannon/ctor2.dora
This PR allows to call the constructor of a class to create a new object. As a consequence StoreField* are now supported.
> cannon: support creation of objects

- dora/src/bytecode/data.rs
- dora/src/bytecode/generator.rs
- dora/src/bytecode/generator_tests.rs
- dora/src/bytecode/writer.rs
- dora/src/cannon/codegen.rs
- tests/cannon/assert1.dora
As mentioned in the code, _cannon_ didn't pass the correct position to the assembler, but created a dummy object. I now have added a `PositionTable` to the bytecode function, which maps the position to the instructions, which require a position. In _cannon_, I then use this map to retrieve the correct position.
> cannon: use correct position for throw/new object/invoke

- dora-boots/assembler.dora
- dora-boots/dce.dora
- dora/src/semck/prelude.rs
- dora/src/typeck/expr.rs
- dora/src/typeck/tests.rs
- dora/stdlib/Byte.dora
- dora/stdlib/Double.dora
- dora/stdlib/Float.dora
- dora/stdlib/Int.dora
- dora/stdlib/Long.dora
- dora/stdlib/Vec.dora
- tests/int1.dora
- tests/limit1.dora
- tests/long3.dora
- tests/num-as.dora
- max/min values got aligned with the general naming scheme
- tried to make right shifts a bit more consistent (see commit message).
@dinfuehr What do you think?
> Various naming cleanups

- Cargo.lock
- dora/Cargo.toml
- dora/src/cpu/arm64.rs
- dora/src/cpu/x64.rs
Functions return `true` on ARM, since the expected instructions have been available for more than 15 years.
> Add support for CPU feature checks

- dora/src/bytecode/generator.rs
- dora/src/bytecode/generator_tests.rs
- dora/src/cannon/codegen.rs
- tests/cannon/fct3.dora
- tests/cannon/fct4.dora
- tests/nil3.dora
Until now, only DirectInvokeVoid was supported. I added the necessary code inside the bytecode generator and implemented the calls in cannon. Additionally, the call checks now for nil before calling the method.
Also I fixed a bug, where following code failed, because the object was not moved to the variable register and added a test case for it.
`let obj = Foo(1); // class Foo(let a: Int)
assert(obj.a == 1);
`
> cannon: direct invoke

- dora/src/bytecode/generator.rs
- dora/src/bytecode/generator_tests.rs
- tests/obj1.dora
- tests/obj2.dora
- tests/obj3.dora
- tests/obj4.dora
- tests/obj5.dora
- tests/obj6.dora
- tests/obj7.dora
- tests/obj8.dora
- tests/obj9.dora
As you mentioned to me, the bytecode generator didn't handle method calls correctly. Instead of moving the called object to the corresponding argument register, it pushed `self` of the current function.
As currently `var_self` hasn't any check to assure the function has self, it doesn't throw an error, but returns the first variable (=`Register(0)`). Because of this, some tests coincidentally worked, as the register for the called object was `Register(0)`. I didn't changed this behavior for now, but added a test to assure the bytecode generator handles this correctly.
> bytecode: fix method call

- dora/src/bytecode/generator.rs
- dora/src/bytecode/generator_tests.rs
- dora/src/cannon/codegen.rs
- tests/virt-call1.dora
As discussed I discontinued my effort to implement the various operations on types and focused to get some of the benchmarks to run. So I implemented the virtual method invocation, which was already defined as bytecode and as visitor functions, but the generator and cannon didn't implement it or not correctly.
The changes are not really complex, mostly some refactoring in the bytecode generator and the implementation details of the corresponding virtual invocation in cannon. At least I think that, maybe I missed the bigger picture.
> cannon: support invocation of virtual calls

- dora/src/cannon/codegen.rs
- tests/cannon/load1.dora
- tests/cannon/store1.dora
cannon ignored the type of the value and tried to store the value into an integer register. I fixed this and also added tests for this.
Additionally, I fixed the test for LoadFieldPtr, as it didn't load any field and instead just returned the argument.
> cannon: fix error when storing float value in field; add test for StoreField

- dora/src/bytecode/generator.rs
- dora/src/bytecode/writer.rs
- dora/src/cannon/codegen.rs
- tests/cannon/int1.dora
As mentioned in #174 this adds support for the missing `!` operator for Int.
> cannon: not intrinsic (int)

- dora/stdlib/Array.dora
- dora/stdlib/Default.dora
- dora/stdlib/Zero.dora
This is the library part for the `Zero` trait – there is a small bit of compiler support necessary right now that records during typechecking whether a class (+ generics) supports zero or not.
The difference between `Default` and `Zero` is that `Default` can be implemented by user code in whatever fashion desired – while `Zero` is more of a marker that any zero-initialized memory of the appropriate size constitutes a valid instance.
This pretty much means only `structs` who do not contain any reference types¹ can be `Zero` – which is good enough for numbers (which are all "honorary" structs, but declared as classes currently), `Option`¹, probably time-/date-related stuff and much more .
¹ We pretend we already live in a world without `nil` here.
² If one squints hard enough.
> Add library code for Zero trait

- dora/src/semck.rs
- dora/src/semck/prelude.rs
- dora/src/semck/typeparamck.rs
- dora/src/ty.rs
- dora/src/typeck/tests.rs
- dora/src/vm.rs
- dora/src/vm/class.rs
- dora/src/vm/vip.rs
- dora/stdlib/Zero.dora
- tests/array/array-zero.dora
@dinfuehr Where should I add that check `if cls.is_zero_initializable {add_zero_trait()/add_zero_impl() }`?
(I could also patch the "well-known" classes like `Int`, `Long` etc. immediately in `prelude::internal_classes`, but I think that would scale poorly as soon as users can define their own zero-initializable structs.)
> Add runtime support for Zero trait

- dora/src/bytecode/generator.rs
Currently the bytecode generator didn't check if a call of type `CallType::Method` really needed the nil check, which is necessary for direct invocation. As a result `1.toString()` was translated to `InvokeDirectPtr(...)`. But when cannon tried to generate the machine code, it checked if the first argument ("self") was indeed of type `BytecodeType::Ptr`. This ultimately failed, as the first argument is `Int`.
I added a check in the generator for`CallType::Method` and if the first argument type is not a Ptr, a flag is set. If the flag is set, `InvokeStatic` is emitted.
> bytecode: emit InvokeStatic for method calls without nil check (e.g. Int.toString())

- dora/src/bytecode/dumper.rs
- dora/src/bytecode/generator.rs
- dora/src/bytecode/generator_tests.rs
- dora/src/bytecode/reader.rs
- dora/src/bytecode/writer.rs
- dora/src/cannon/codegen.rs
- dora/src/semck/clsdefck.rs
- dora/src/semck/extensiondefck.rs
- dora/src/semck/globaldef.rs
- dora/src/semck/impldefck.rs
- dora/src/semck/moduledefck.rs
- dora/src/semck/traitdefck.rs
- dora/src/vm.rs
- dora/src/vm/fct.rs
As discussed, to support function and class type params when calling a method, I added a `FctDef`. This is similar to `ClassDef` the specialization of a `Fct` with the corresponding type params.
The bytecode now uses the `FctDefId` instead of `FctDef` when referencing to a function. Cannon then uses this id to retrieve the corresponding type params and will generate the machine code accordingly.
> bytecode/cannon/vm: Add specializations for functions to vm and use in bytecode/cannon

- dora-parser/src/parser.rs
The keyword was printed instead of the offending annotation, e. g.:
@open @open
class Foo()
Before: redundant annotation class
After:  redundant annotation open
> Fix the error messages for annotation parsing problems

- dora/src/bytecode/data.rs
- dora/src/bytecode/dumper.rs
- dora/src/bytecode/generator.rs
- dora/src/bytecode/generator_tests.rs
- dora/src/bytecode/reader.rs
- dora/src/bytecode/writer.rs
- dora/src/cannon/codegen.rs
- dora/src/vm.rs
- tests/cannon/evaluation-order1.dora
- tests/evaluation-order1.dora
I started the implementation for array support in cannon. For now, only the allocation of a new Array is supported and only if the array is not a array of tuples, objects or unit, or is of length 0.
Before I continue, I thought it would be a good idea to get your feedback on this. Especially, I would like your opinion on my decision to change the order of how the arguments of a call are handled. The reason behind this decision is the length argument of the array, which is needed to calculate the size of the array. I could have just handled this case differently, but I see no reason, why this would be necessary.
Next, I would add functionality for set&get of array values, before I fill the missing types of arrays and the various edge cases (e.g. no length argument.)
> cannon: support for array

- dora/src/error/msg.rs
- dora/src/semck.rs
- dora/src/semck/clsdefck.rs
- dora/src/semck/fctdefck.rs
- dora/src/semck/globaldef.rs
- dora/src/semck/impldefck.rs
- dora/src/semck/moduledefck.rs
- dora/src/semck/nameck.rs
- dora/src/stdlib.rs
- dora/src/sym.rs
- dora/src/typeck/expr.rs
- dora/src/typeck/tests.rs
- dora/src/vm.rs
This reduces the amount of "surprising" name clashes¹ and
is required for both modules and annotations to work well:
- It allows modules to have the same name as a class or struct.
This is a stepping stone to replacing @static members with members inside modules.
- It avoids annotation names clashing with function names (like in `fun test()`).¹
¹ Annotations (which are types) start with a lowercase letter because it looks more familiar/
more like a modifier and draws away less attention from the keywords that follows.
Nevertheless, we get some additional benefit out of it:
It makes annotations unlikely to ever clash with another type definition,
because classes, traits, structs all start with an uppercase letter by convention.
> Split terms and types into separate namespaces

- dora-parser/src/ast.rs
- dora-parser/src/ast/dump.rs
- dora-parser/src/ast/visit.rs
- dora-parser/src/lexer.rs
- dora-parser/src/lexer/token.rs
- dora-parser/src/parser.rs
- dora/src/baseline/codegen.rs
- dora/src/bytecode/generator.rs
- dora/src/semck/returnck.rs
- dora/src/typeck/expr.rs
- dora/src/typeck/tests.rs
- Try to sort the keywords into categories.
- Made `parse_comma_list` a bit more generic by allowing to specify the separator.
- Drop `~` which is not used anywhere, as we use `!` as bitwise negation.
- Drop `+=`, as it's not used – given how it makes it harder to read code (another precedence rule to keep in mind) I also think it would be better to simply not have it (just like we do not have `++`, `--`).
> Cleanup parser

- dora/src/cannon/codegen.rs
As discussed, I will split #195 into several smaller PR to reduce the complexity. The first PR refactors the store and load to the bytecode registers to a explicit function.
> cannon: refactor store and load register to method

- tools/tester.rb
This PR adds the possibility to define a time-out for a test file  with `//= timeout <value>`. Currently, the timeout is optional. Tests without it, run as before. Should we set a time-out as default, so we can guarantee, that the tests don't run indefinitely?
The function to start the process within a time-out block is from https://gist.github.com/pasela/9392115. I used this, as there is a lot of text to find on problems with time-out in ruby (e.g. https://redmine.ruby-lang.org/issues/4681)  and it would be pointless to invest a lot of time in this problem. ;)
> test-runner: allow to define timeout for test cases

- dora/src/baseline/codegen.rs
- dora/src/bytecode/generator.rs
- dora/src/semck/clsdefck.rs
- dora/src/semck/fctdefck.rs
- dora/src/semck/globaldef.rs
- dora/src/semck/moduledefck.rs
- dora/src/semck/nameck.rs
- dora/src/semck/specialize.rs
- dora/src/ty.rs
- dora/src/typeck/expr.rs
- dora/src/typeck/lookup.rs
- dora/src/typeck/tests.rs
- dora/src/vm/module.rs
- dora/src/vm/src.rs
- tests/module/module1.dora
- tests/module/module2.dora
This means that
```
module Foo {
fun foo() -> String = "module";
fun bar() -> String = Foo().foo();
fun baz() -> String = Foo::foo();
}
fun main() {
assert(Foo::foo() == "module");
assert(Foo::bar() == "class");
assert(Foo::baz() == "module");
}
```
works now.
The only remaining usages of `@static` in the standard library are in the
`Default` and `Zero` traits – I have a concept for them too, but this requires
additional preparations in other places, which exceed the scope of this PR.
> Module methods

- Cargo.lock
- dora-parser/Cargo.toml
- dora/Cargo.toml
- dora/src/driver/cmd.rs
When you run `cargo tree -d` (requires cargo 1.44+) , you see a lot of
duplication is dependencies. This duplication usually affects both
compile times and the binary size. Here, the major reason for
duplication was older version of `docopt` in dora and `parking_lot` in
dora-parser. Also, this older version of `docopt` uses `rustc_serialize`
which is deprecated in favour of `serde`.
https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay
I have upgraded the `docopt`, `parking_lot` and patch versions for some
other dependencies. There are no duplications now. It reduces the total
number of dependencies from 106 to 87.
Although there was negligible improvement in build time, it reduces the
size of release binary by more than 1MB (for `amd64-linux` target).
> Fixed duplication in dependencies.

- dora/stdlib/HashMap.dora
- dora/stdlib/HashSet.dora
In case of HashMap, this further reduces the amount of `nil`s we produce.
> Return Option for HashMap#remove and Bool for HashSet#remove

- Cargo.lock
- dora/Cargo.toml
- dora/src/cpu/x64.rs
Fix https://github.com/dinfuehr/dora/issues/257.
> x64: drop raw-cpuid dependency, use feature from std library

- dora/src/language/access.rs
- dora/src/language/fctbodyck/body.rs
- dora/src/language/globaldef.rs
- dora/src/language/importck.rs
- dora/src/language/readty.rs
- dora/src/language/sem_analysis.rs
- dora/src/language/sym.rs
- dora/src/vm.rs
- dora/src/vm/namespaces.rs
This is needed to initialize modifiers later on.
> change `Vec<NamespaceData>` → `Vec<RwLock<NamespaceData>>` to allow mutation of namespaces later on
